/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_FDBG_TO_COMPUTER_PB_H_INCLUDED
#define PB_FDBG_TO_COMPUTER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _fdbg_Ack {
    char dummy_field;
} fdbg_Ack;

typedef PB_BYTES_ARRAY_T(64) fdbg_WriteMemory_bytes_t;
typedef struct _fdbg_WriteMemory {
    uint64_t initial_addr;
    fdbg_WriteMemory_bytes_t bytes;
    bool validate;
} fdbg_WriteMemory;

typedef struct _fdbg_ReadMemory {
    uint64_t initial_addr;
    uint32_t sz;
} fdbg_ReadMemory;

typedef struct _fdbg_ToComputer {
    pb_size_t which_message;
    union {
        fdbg_Ack ack;
        fdbg_WriteMemory write_memory;
        fdbg_ReadMemory read_memory;
    } message;
} fdbg_ToComputer;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define fdbg_Ack_init_default                    {0}
#define fdbg_WriteMemory_init_default            {0, {0, {0}}, 0}
#define fdbg_ReadMemory_init_default             {0, 0}
#define fdbg_ToComputer_init_default             {0, {fdbg_Ack_init_default}}
#define fdbg_Ack_init_zero                       {0}
#define fdbg_WriteMemory_init_zero               {0, {0, {0}}, 0}
#define fdbg_ReadMemory_init_zero                {0, 0}
#define fdbg_ToComputer_init_zero                {0, {fdbg_Ack_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define fdbg_WriteMemory_initial_addr_tag        1
#define fdbg_WriteMemory_bytes_tag               2
#define fdbg_WriteMemory_validate_tag            3
#define fdbg_ReadMemory_initial_addr_tag         1
#define fdbg_ReadMemory_sz_tag                   2
#define fdbg_ToComputer_ack_tag                  1
#define fdbg_ToComputer_write_memory_tag         2
#define fdbg_ToComputer_read_memory_tag          3

/* Struct field encoding specification for nanopb */
#define fdbg_Ack_FIELDLIST(X, a) \

#define fdbg_Ack_CALLBACK NULL
#define fdbg_Ack_DEFAULT NULL

#define fdbg_WriteMemory_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   initial_addr,      1) \
X(a, STATIC,   SINGULAR, BYTES,    bytes,             2) \
X(a, STATIC,   SINGULAR, BOOL,     validate,          3)
#define fdbg_WriteMemory_CALLBACK NULL
#define fdbg_WriteMemory_DEFAULT NULL

#define fdbg_ReadMemory_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   initial_addr,      1) \
X(a, STATIC,   SINGULAR, UINT32,   sz,                2)
#define fdbg_ReadMemory_CALLBACK NULL
#define fdbg_ReadMemory_DEFAULT NULL

#define fdbg_ToComputer_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,ack,message.ack),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,write_memory,message.write_memory),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,read_memory,message.read_memory),   3)
#define fdbg_ToComputer_CALLBACK NULL
#define fdbg_ToComputer_DEFAULT NULL
#define fdbg_ToComputer_message_ack_MSGTYPE fdbg_Ack
#define fdbg_ToComputer_message_write_memory_MSGTYPE fdbg_WriteMemory
#define fdbg_ToComputer_message_read_memory_MSGTYPE fdbg_ReadMemory

extern const pb_msgdesc_t fdbg_Ack_msg;
extern const pb_msgdesc_t fdbg_WriteMemory_msg;
extern const pb_msgdesc_t fdbg_ReadMemory_msg;
extern const pb_msgdesc_t fdbg_ToComputer_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define fdbg_Ack_fields &fdbg_Ack_msg
#define fdbg_WriteMemory_fields &fdbg_WriteMemory_msg
#define fdbg_ReadMemory_fields &fdbg_ReadMemory_msg
#define fdbg_ToComputer_fields &fdbg_ToComputer_msg

/* Maximum encoded size of messages (where known) */
#define FDBG_TO_COMPUTER_PB_H_MAX_SIZE           fdbg_ToComputer_size
#define fdbg_Ack_size                            0
#define fdbg_ReadMemory_size                     17
#define fdbg_ToComputer_size                     81
#define fdbg_WriteMemory_size                    79

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
