/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "to-debugger.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fdbg_Ready, fdbg_Ready, AUTO)


PB_BIND(fdbg_AckResponse, fdbg_AckResponse, AUTO)


PB_BIND(fdbg_WriteMemoryConfirmation, fdbg_WriteMemoryConfirmation, AUTO)


PB_BIND(fdbg_MemoryUpdate, fdbg_MemoryUpdate, AUTO)


PB_BIND(fdbg_ToDebugger, fdbg_ToDebugger, AUTO)



