/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "to-computer.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fdbg_Ack, fdbg_Ack, AUTO)


PB_BIND(fdbg_WriteMemory, fdbg_WriteMemory, AUTO)


PB_BIND(fdbg_ReadMemory, fdbg_ReadMemory, AUTO)


PB_BIND(fdbg_ToComputer, fdbg_ToComputer, AUTO)



