/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "to-computer.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Ack, Ack, AUTO)


PB_BIND(WriteMemory, WriteMemory, AUTO)


PB_BIND(ReadMemory, ReadMemory, AUTO)


PB_BIND(ToComputer, ToComputer, AUTO)



