/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "to-debugger.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AckResponse, AckResponse, AUTO)


PB_BIND(WriteMemoryConfirmation, WriteMemoryConfirmation, AUTO)


PB_BIND(MemoryUpdate, MemoryUpdate, AUTO)


PB_BIND(ToDebugger, ToDebugger, AUTO)



